### PR TITLE
Added future courses for example CS student

### PR DESCRIPTION
**Pull request by drewvolz**
These are my courses for the CS major.

### CODE REVIEW

**Comment by hawkrives** [comment]
So I'm sure that you noticed that that set of courses fails to graduate...

I just dropped it into Cosmos, which I worked on some more today, and got this:

screen shot 2015-07-22 at 11 55 52 pm

1. Man, that's nicer to debug with than the JSON output in a terminal.
2. It appears that the problems are that we now require a math course, and you don't have a "valid" elective chosen...

**Comment by hawkrives** [comment]
(To get it into Cosmos, I ran `./bin/evaluate example-students/computer-science-load-1.json --json | pbcopy` – `pbcopy` is an OS X built-in command to copy stdin to the clipboard. Then I made a new file under `cosmos/fixtures/area/` – say, `compsci-load-1.js`. Then I typed `export default `, and pasted the JSON. Cosmos then picked up the new file and rendered it!)

**Comment by drewvolz** [comment]
I had a math course listed as CS. But my proof writing course should have passed? I have satisfied MATH 282.

Additionally, does my CSCI 300 (mobile web graphics) not count towards the elective requirement (unless it is PDC)?

**Comment by hawkrives** [comment]
The math one is a bit weird… oh. 

Because 282 is topics, it only counts if the course object (in JSON) has matching "year" and "semester" properties. 

I'll have to think about why Mwg isn't counting.

**Comment by drewvolz** [comment]
Great. I'm glad we found these  problems quickly

**Comment by hawkrives** [comment]
Yes indeed.

**Comment by hawkrives** [comment]
Oh.

Figured out MWG.

Remember how you didn't have a year/semester on the Math course?

Well, you don't have one on MWG, either.

Since we specified MWG by the year/semester selector, both year and semester must be present in order for it to match.

**Pull request merged**
